basic structure setup
AzizRAA/To-Do-List pull request #1
Opened 2022-07-15 15:42 UTC by AzizRAA

2022-07-15 16:17 UTC, HAMMAS-SALEEM reviewed
Good Changes

2022-07-15 17:20 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @AzizRAA :wave:

### Highlights :1st_place_medal:

:heavy_check_mark: Following Linters 
:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Following HTML, CSS best practices


Good job on implementing some of the changes requested by the previous reviewer but there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 17:20 UTC, HAMMAS-SALEEM commented on webpack.config.js
>      print: './src/print.js',
- [ ] You can remove `print: './src/print.js',` because the entry should have only one file and all the other files should be the modules :+1:

2022-07-15 17:20 UTC, HAMMAS-SALEEM commented on src/index.js
> +`;
![missing requirements (copy)](https://user-images.githubusercontent.com/93039359/179273446-971682f1-7e6d-4c7d-91eb-c65a0c0f9b70.png)

- [ ] It's great that you are using HTML as a template :clap: but you are not implementing all the requirements shown in the red boxes in the image above :up:

2022-07-15 17:20 UTC, HAMMAS-SALEEM commented on src/index.html
> +    </main>
- [ ] Instead of using a `main` tag please use `div` tag as mentioned in your requirements :+1:

2022-07-15 17:20 UTC, HAMMAS-SALEEM commented on webpack.config.js
>        {
![package json (copy)](https://user-images.githubusercontent.com/93039359/179274706-2b8c74b9-780b-4ce5-b654-ccbbcbb6346b.png)

Please add the above line shown in the yellow box in your package.json file to let your server start your project. :+1:

2022-07-15 17:20 UTC, HAMMAS-SALEEM commented on dist/print.bundle.js
> +
### Your Readme Getting Started Section
![getting-started-fixable](https://user-images.githubusercontent.com/93039359/179275040-3f07add4-df95-47d9-9b2f-6a6883c59433.png)
### Add Following Commands in your Getting Started Section
![getting-started-fixed](https://user-images.githubusercontent.com/93039359/179275098-e52fd87a-8e2a-4677-83a2-c52dc14e8ed2.png)

- [ ] Please the following commands in your Readme Getting Started Section :+1: as shown in the image above. :arrow_up: Because getting started section let other people know how to start you project in their machine :blush:

2022-07-16 15:59 UTC, Ismailco requested changes
### Hi @AzizRAA, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 15:59 UTC, Ismailco commented on src/index.js
> +  </div>`;
- [ ] As the previous reviewer mentioned you need to create an array with the todo task and iterate over it to populate the Html, kindly implement this it's a requirement

2022-07-16 15:59 UTC, Ismailco commented on src/index.js
> +  </div>`;
- [ ] As the previous reviewer mentioned your todo list tasks should be rendered to the page when the app loaded

2022-07-16 15:59 UTC, Ismailco commented on src/index.js
> ![package json (copy)](https://user-images.githubusercontent.com/93039359/179274706-2b8c74b9-780b-4ce5-b654-ccbbcbb6346b.png)
> 
> Please add the above line shown in the yellow box in your package.json file to let your server start your project. +1


- [ ] As suggested by the previous reviewer kindly add the start script to the package.json so the development server can be started, also don't forget to install the `webpack-dev-server' package.

2022-07-16 15:59 UTC, Ismailco commented on src/index.js
> +// Lists
> ### Your Readme Getting Started Section
> ![getting-started-fixable](https://user-images.githubusercontent.com/93039359/179275040-3f07add4-df95-47d9-9b2f-6a6883c59433.png)
> 
> ### Add Following Commands in your Getting Started Section
> ![getting-started-fixed](https://user-images.githubusercontent.com/93039359/179275098-e52fd87a-8e2a-4677-83a2-c52dc14e8ed2.png)
> 
> * [ ]  Please the following commands in your Readme Getting Started Section +1 as shown in the image above. arrow_up Because getting started section let other people know how to start you project in their machine blush


- [ ] Your Getting start section need's some modifications, kindly implement the changes suggested by the previous reviewer

2022-07-16 15:59 UTC, Ismailco commented on src/style.css
> +.main {
- [ ] [OPTIONAL] Your app should be styled according to the given design, kindly consider styling your app to look like the provided design

|Your design|Given design|
|-|-|
|![Screenshot_20220716_164705](https://user-images.githubusercontent.com/25227022/179362378-078e3d06-a8e9-4af7-9c04-4aec200870b7.png)|![Screenshot_20220716_165719](https://user-images.githubusercontent.com/25227022/179362411-f558f17d-8a16-4f36-b8f7-0c148ad68ffc.png)|

2022-08-12 15:40 UTC, closed without merging